# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [14]:
# Tu respuesta aquí

nombre = "Daniel"
edad = 32

print(f"Hola, me llamo {nombre} y tengo {edad} anios.")


Hola, me llamo Daniel y tengo 32 anios.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [15]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
# Imprime el primer numero y el ultimo elemento  
print("primer numero de la listas:", numeros[0])
print("Ultimo numero de la lista:", numeros[-1])
print("---------------------------------------------")

#Imprime los tres primeros elementos usando slicing
print("Los tres primeros numeros de la listas son:", numeros[0:3])
print("---------------------------------------------")

#Agregar el numero 99 al final de la listas
numeros.append(99)
print("Lista con el numero 99 agregado al final:\n", numeros)


primer numero de la listas: 10
Ultimo numero de la lista: 15
---------------------------------------------
Los tres primeros numeros de la listas son: [10, 25, 3]
---------------------------------------------
Lista con el numero 99 agregado al final:
 [10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [16]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí

if estudiante["promedio"] >= 6:
    print(f"{estudiante['nombre']} esta aprobado en la {estudiante['carrera']} con un promedio de {estudiante['promedio']}")
else:
    print(f"{estudiante['nombre']} esta reprobrado en la {estudiante['carrera']} con un promedio de {estudiante['promedio']}")

Carlos esta aprobado en la Sistemas con un promedio de 7.5


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [17]:
# Tu respuesta aquí

base = 5
altura = 10

def calcular_area (base, altura):
    area = (base * altura) / 2
    return area

area_triangulo = calcular_area(base, altura)
print(f"El area del triangulos con base {base} y altura {altura} es {area_triangulo}")

El area del triangulos con base 5 y altura 10 es 25.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [21]:
# Tu respuesta aquí

cuadrados = [x**2 for x in range(1, 11)]
print("La lista con numeros al cuadrado del 1 al 10 es:\n",cuadrados)


La lista con numeros al cuadrado del 1 al 10 es:
 [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [22]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [30]:
# Tu respuesta aquí

# Arreglo con valores específicos
arreglo = np.array([1.5, 2.5, 3.5, 4.5])
print(arreglo)
print("shape:", arreglo.shape)
print("dtype:", arreglo.dtype)
print("---------------------------------------------")

# Matriz de ceros 3x4
ceros = np.zeros((3, 4))
print(ceros)
print("shape:", ceros.shape)
print("dtype:", ceros.dtype)
print("---------------------------------------------")

# 6 valores igualmente espaciados entre 0 y 1
arreglo_valores = np.linspace(0, 1, 6)
print(arreglo_valores)
print("shape:", arreglo_valores.shape)
print("dtype:", arreglo_valores.dtype)


[1.5 2.5 3.5 4.5]
shape: (4,)
dtype: float64
---------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape: (3, 4)
dtype: float64
---------------------------------------------
[0.  0.2 0.4 0.6 0.8 1. ]
shape: (6,)
dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [35]:
a = np.arange(1, 13)

# Tu respuesta aquí

matriz = a.reshape(3, 4)
print(matriz)
print("---------------------------------------------")
print("Valor máximo:", matriz.max())
print("---------------------------------------------")
print("Valor mínimo:", matriz.min())
print("---------------------------------------------")
print("Índice del máximo:", matriz.argmax())


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------------------------------------
Valor máximo: 12
---------------------------------------------
Valor mínimo: 1
---------------------------------------------
Índice del máximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [44]:
# Tu respuesta aquí

arreglo_1 = np.random.randint(1, 21, 5)
arreglo_2 = np.random.randint(1, 21, 5)
print("arreglo_1:", arreglo_1)
print("arreglo_2:", arreglo_2)
print("---------------------------------------------")
print("Suma:", arreglo_1 + arreglo_2)
print("---------------------------------------------")
print("Resta:", arreglo_1 - arreglo_2)
print("---------------------------------------------")
print("Multiplicación:", arreglo_1 * arreglo_2)


arreglo_1: [ 8 20  6 11 16]
arreglo_2: [15  8  1 12 14]
---------------------------------------------
Suma: [23 28  7 23 30]
---------------------------------------------
Resta: [-7 12  5 -1  2]
---------------------------------------------
Multiplicación: [120 160   6 132 224]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [47]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí

aprobadas = notas[notas >= 6]
print("Las notas aprobadas son:", aprobadas)


Las notas aprobadas son: [ 8.5  6.   9.2  7.8 10. ]
